### ISSUE TITLE
cosmetic: have 50% and 90% CI options as their own boxes in legend, rather than two clicks away

### ISSUE THREAD

**Issue by nickreich** [reichlab/flusight#28]

**Comment by lepisma** [comment]
Will add a dropdown in legend for it.

**Comment by nickreich** [comment]
I think it'd be preferable to not have a dropdown, but just two boxes in the legend that say "90% CI" and "50% CI" that would replace the box right now that you click to get the options and isn't obviously a CI selector box. Does that make sense?

**Comment by lepisma** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2487306/20416044/46311f24-ad0a-11e6-9e15-b9c4838435ca.png)


I was wondering about the amount of entries in legend. There will be one more for `lagged` data (used for predictions). A dropdown (something like above) or a double throw switch was what I meant for the *in legend* entry.

**Comment by nickreich** [comment]
I was thinking having the CI options in the blue-outlined legend icons to the right of the legend itself.  Right above the navigation arrows.

**Comment by nickreich** [comment]
Sorry that I wasn't clear the first time around.

**Comment by lepisma** [comment]
![image](https://cloud.githubusercontent.com/assets/2487306/20416197/4ecc4978-ad0b-11e6-9c0e-1fe64c4b10df.png)

This way ?

**Comment by nickreich** [comment]
Yes! Would it be possible to squeeze in a "CI" in the label somewhere?

**Comment by lepisma** [comment]
It would be hard to put the text inside and keep it readable.

Here is how it might look with a switch in prediction section of legend which is also a *single-click-to-change* control.
![untitled](https://cloud.githubusercontent.com/assets/2487306/20452962/05101ee2-ade5-11e6-9471-d54cfc4f38be.png)

**Comment by nickreich** [comment]
That looks good!

-- 
Nicholas G. Reich, Ph.D.
Assistant Professor
Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

413.545.4534
nick@schoolph.umass.edu
http://reichlab.github.io/
on twitter: @reichlab
