### ISSUE TITLE
when historical line is highlighted, can it also be brought to front of other lines?

### ISSUE THREAD

**Issue by nickreich** [reichlab/flusight#29]

**Comment by lepisma** [comment]
I could move the currently highlighted historical line in front of

1. All other historical lines
2. Above the predictions and actual lines too

I guess, you are talking about the second one.

**Comment by nickreich** [comment]
@elray1 what do you think? I might vote for (1), as I think it might get distracting to have it flickering over the predictions everytime you pass over a line.
