### ISSUE TITLE
add analytics/visit counter to flusight

### ISSUE THREAD

**Issue by nickreich** [reichlab/flusight#30]
I have a free account through statcounter.com and have a few sites set up there, but am not sure what the best platform is for this these days.

**Comment by lepisma** [comment]
[Google analytics](https://www.google.com/analytics/#?modal_active=none) is an alternative. Since you already have other sites set up at statcounter, we should go with that (doesn't really matter unless we are looking for some specific stat/interpretation).

**Comment by nickreich** [comment]
Just sent you info about setting up stat counter on flu sight.

-- 
Nicholas G. Reich, Ph.D.
Assistant Professor
Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

413.545.4534
nick@schoolph.umass.edu
http://reichlab.github.io/
on twitter: @reichlab
