### ISSUE TITLE
Remove movement restriction in plots for future times

### ISSUE THREAD

**Issue by lepisma** [reichlab/flusight#66]
Since we have models like KDE which have predictions for the whole season, it doesn't make any sense to restrict the movement in only the list of weeks for which we have actual/observed data.

**Comment by nickreich** [comment]
Not sure I agree. I think the movement to a timezero in the future not be allowed. It confuses the definition/purpose of a timezero  otherwise.

**Comment by lepisma** [comment]
Right.

As of now you might be able to move in the future if you use controls from d3-foresight (like mouse click on chart and arrow buttons). The keyboard buttons work in the restricted range. This is because of some conflict between these two ranges and will be fixed in a few commits.
